### PR TITLE
Adds Accesses for Court Clerk/Bailiff

### PR DESCRIPTION
**Pull request by XanderDox**
This adds legal access and sec door access to both City Hall Secretary and legal access to City Hall Security.

The purpose of this is so the City Hall Secretary alt title of Court Clerk can enter the PD's front doors for Court business, and enter the Judge's stand to hand them paperwork and work the desks there.

As well, this will allow the Bailiff to properly bailiff as they will now be able to access the side windoors of the court and the judge's stand without the Judge's help.

### CODE REVIEW

**Comment by GeneriedJenelle** [comment]
I'd rather the door accesses for the courtroom were changed rather than give baliffs/city hall guards security access. A lot of them believe they are optional "police officers", and we try to discourage that.

**Comment by XanderDox** [comment]
@GeneriedJenelle City Hall Sec already have front door PD access from before this PR, this is only giving that to assistant clerks. I can remove it from both if you'd like?

**Comment by XanderDox** [comment]
Updated:

Removes PD Access from City Hall Guard and City Hall Secretary

Adds warrant access to Prosecutors in line with new criminal justice changes.

@GeneriedJenelle

**Comment by GeneriedJenelle** [comment]
Ah you don't need to remove sec door access for prosecutors, they actually need that. I just meant for secretaries. 

If you can readd sec door access for prosecutors, would be appreciated.

**Comment by XanderDox** [comment]
Prosecutors didn't lose sec door access.

**Pull request merged**
