### PR TITLE
renames spaceacillin to penicillin

### PR DESCRIPTION
**Pull request by Myoblongvagooglia**
am done

### CODE REVIEW

**Comment by UndeadNappist** [comment]
Alot of things have become immune to it in recent years. Also, penicillin is an organic formula squeezed out by a bacteria with the ingredients C16H18N2O4S, and is a real chemical.

Some things were named because people didn't think very carefully about them - 'plasma' - but this probably isn't one of them.

**Comment by Myoblongvagooglia** [comment]
Spaceacillin was/is an intentional play on penicillin.

Furthermore, penicillin is part of the ever-expanding family of antibiotics called beta-lactams. You've probably prescribed it's cousin, amoxicillin, at one point. They are commonly used today and to claim that they are ineffective is a gross simplification of many, many compounds. 

Lastly, I have written brief lore on this in an unreleased announcement from the Ministry of Health. It shares the same name but is far more productive than what we know in 2019, seeing as our setting takes place five hundred years in the future.

**Comment by UndeadNappist** [comment]
> Furthermore, penicillin is part of the ever-expanding family of antibiotics called beta-lactams. You've probably prescribed it's cousin, amoxicillin, at one point. They are commonly used today and to claim that they are ineffective is a gross simplification of many, many compounds.

>Some things were named because people didn't think very carefully about them - 'plasma' - but this probably isn't one of them.

You print spacecillian out of a chemistry machine. I also didn't say they were ineffective. I just said that a lot of things are becoming immune or resistant to them. In 500 years, I imagine it would get worse.

> Lastly, I have written brief lore on this in an unreleased announcement from the Ministry of Health. It shares the same name but is far more productive than what we know in 2019, seeing as our setting takes place five hundred years in the future. It is not recent years.

Yes, because naming something exactly identical to something that already exists but having it completely different while having some background lore reason dropped in some place that nobody will likely read will definitely make it less confusing for people entering the game and reading the narrative.

This is being written and created for the modern reader.

There's no reason to do this, it doesn't make sense, and it would increase confusion.

**Comment by Myoblongvagooglia** [comment]
You are making a lot of assumptions. The wiki has already been updated to match penicillin. There has been a lore explanation made for this change. 

Thank you for your opinion, but this is being merged.

**Comment by Jeff-Dome** [comment]
Commonly, Virus and Bacterium only become resistant by over using the drug or substance, E.g. for example 2019 hospital as the cleaning chemicals they use are quite harsh to kill off large amount of bacterium as well spraying with anti-biotics. Resistant can spread but wise, there is other forms or removing virus as well if they become resistant to the chemical, for example in game, Corophizine. Now corophizine is a star Trek chem but that doesn't detract from the point that is used form other things. Besides over 500 years, I'm sure if they would of been resistant which in fact they already as for example, the drug in game only halts progression of some types of Virus, (Ones from Viro) and as well the drug taking large amount of time in game to reduce infection levels from (T3 to T2) infections, thus implying already that the viruses are already in fact resistant to the drug either streaming from surviving of the virus or from the over use of it.

**Comment by UndeadNappist** [comment]
> You are making a lot of assumptions. The wiki has already been updated to match penicillin. There has been a lore explanation made for this change.
> 
> Thank you for your opinion, but this is being merged.

You successfully failed to address any of the points I made and instead quoted something almost completely irrelevant to the topic at hand, then attempted to make a claim that what I stated were opinions.

Please refer to the attached chart below with the highlighted sections in RED.
image

**Comment by Myoblongvagooglia** [comment]
You aren't being attacked. This is an unnecessary overreaction to me not agreeing with you.

**Comment by UndeadNappist** [comment]
>Thank you for your opinion, but this is being merged.
>You aren't being attacked. This is an unnecessary overreaction to me not agreeing with you.

>You are making a lot of assumptions. The wiki has already been updated to match penicillin. There has been a lore explanation made for this change.

>Yes, because naming something exactly identical to something that already exists but having it completely different while having some background lore reason dropped in some place that nobody will likely read will definitely make it less confusing for people entering the game and reading the narrative.

image

**Comment by Chrysblade** [comment]
Reminder that rule 1 exists and that we need to keep criticism constructive.

**Comment by Chrysblade** [comment]
Would it make you feel better if instead of Penicillin it was called Neopenicillin? Or even Neocillin? In-game, spaceallin works as an anti-infectant so we could alternatively call it simply anti-infectant.

No need to argue about it, and definitely no need to pull charts.
There is no "facts" and "logic" about arguing in this situation.
Both of you are being quite ridiculous and petty.

**Comment by UndeadNappist** [comment]
> Would it make you feel better if instead of Penicillin it was called Neopenicillin? Or even Neocillin? In-game, spaceallin works as an anti-infectant so we could alternatively call it simply anti-infectant.

Sure, but then... why even rename it in the first place? The whole point is to not cause players running into the chemical to become confused, entertain them, and also give them an immediate reason to understand what the chemical might do based on the name.

>There is no "facts" and "logic" about arguing in this situation.
>Yes, because naming something exactly identical to something that already exists but having it completely different while having some background lore reason dropped in some place that nobody will likely read will definitely make it less confusing for people entering the game and reading the narrative.

> No need to argue about it, and definitely no need to pull charts.
> Both of you are being quite ridiculous and petty.
Absolutely.

**Comment by Myoblongvagooglia** [comment]
> Sure, but then... why even rename it in the first place? The whole point is to not cause players running into the chemical to become confused, entertain them, and also give them an immediate reason to understand what the chemical might do based on the name.

It's being renamed due to the space reference. They aren't appropriate for the setting and I'm slowly working on weeding those out.

> Yes, because naming something exactly identical to something that already exists but having it completely different...

Penicillin V potassium is used to treat infections, specifically bacterial. It isn't a huge stretch and isn't completely different. 

> ...while having some background lore reason dropped in some place that nobody will likely read will definitely make it less confusing for people entering the game and reading the narrative.

It's on the Wiki's medical guides for player accessibility. I even consulted some of our medical mains before even making this PR. They were all in agreement. This is what I meant by assumptions.

**Comment by UndeadNappist** [comment]
> It's being renamed due to the space reference. They aren't appropriate for the setting and I'm slowly working on weeding those out.

You are removing a joke because it bothers you.

> > Yes, because naming something exactly identical to something that already exists but having it completely different...

> Penicillin V potassium is used to treat infections, specifically bacterial. It isn't a huge stretch and isn't completely different.
 
Penicillin V is C16H17KN2O5S. That is a real chemical.
(C3H6O + C? + C12H22O11) + (C3H6O + P? + C12H22O11) is the chemical composition of the space-vaccine and it is not a real chemical.
A chainsaw and a laser-saw cut trees.
I would not arbitrarily rename a laser-saw to just 'chainsaw.'

> It's on the Wiki's medical guides for player accessibility. I even consulted some of our medical mains before even making this PR. They were all in agreement. This is what I meant by assumptions.

Do you honestly think that players that have a difficult enough time reading the rules will bother sitting down and reading some lore explanation for a name?

> ...while having some background lore reason dropped in some place that nobody will likely read will definitely make it less confusing for people entering the game and reading the narrative.

**Comment by Chrysblade** [comment]
Myo is not "removing a joke" because it "bothers" him. He is removing all references to space because the server is not based in space, it is based in a city on a planet.

Who cares if Penicillin V is a real chemical or not, I support the changes from spaceacillin to penicillin simply due to the fact that it makes sense. Spaceacillin is clearly a play on penicillin. No one is changing laser-saw to chainsaw and that isn't a very good comparison.

I don't think that players, whether they read the rules or not, are going to be confused or upset by the change from spaceacillin to penicillin.

Again, let's not argue about this.
If it gets merged then it gets merged. If it doesn't, then there is a reference to space that shouldn't be there.

**Comment by Myoblongvagooglia** [comment]
I am removing a reference to space because we aren't in space.

> Do you honestly think that players that have a difficult enough time reading the rules will bother sitting down and reading some lore explanation for a name?

It is in the guide. Penicillin. There are no spaceacillin mentions whatsoever. Anyone who is confused in-game about this can easily access the wiki and see, oh, penicillin treats infections. Cool. This can happen regardless if they know the lore explanation or not.

**Comment by JessiCode5** [comment]
At this point I feel as if you're arguing to argue. The change makes sense, this being a planet, and the change is reasonable. This is being extended out **way** more than it should be, and is frankly quite annoying.

**Comment by Myoblongvagooglia** [comment]
Received permission from the loremaster, as requested. All should be well and this is ready to merge.

**Comment by GeneriedJenelle** [comment]
I'm merging this, but let me add in a comment. You don't need to remove all references to space, nearly everyone on Pollux visits or has visited space. Space is a part of civilian life, people travel through it, comment on it, have worked in it. etc.

But in this case I don't mind this change either, both sides have solid points. It's also fine either way. I'm quite fond of Neopenicillin as a name, actually.

**Comment by Myoblongvagooglia** [comment]
I don't intend on removing every reference to space, for clarity. Some are fine. But spaceacillin, to me, shouldn't exist on a planet since it's literally marketed as "curing diseases you'd often find in space"

**Pull request merged**
