### PR TITLE
Removes Fire Department

### PR DESCRIPTION
**Pull request by WorldServerDeath**
Turns Fire Department into Maintenance.
Moves Medic back to hospital.

### CODE REVIEW

**Comment by GeneriedJenelle** [comment]
You sure you want to entirely remove it?

**Comment by GeneriedJenelle** [comment]
You sure you want to entirely remove it?

**Comment by XanderDox** [comment]
@WorldServerDeath consider moving custodial under the new maintenance team?

**Comment by WorldServerDeath** [comment]
For the time, yeah. If we develop more into fires it could be reverted in the future. @XanderDox, it is already moved in this PR.

**Pull request merged**
