### PR TITLE
Changes teen scale to what it was before.

### PR DESCRIPTION
**Pull request by GeneriedJenelle**
I got bullied into this.

### CODE REVIEW

**Comment by Myoblongvagooglia** [comment]
### **Good.**

**Comment by GeneriedJenelle** [comment]
haha tfw your teen still borked. (honestly though, I reverted my changes, could it be something else?)

**Comment by Myoblongvagooglia** [comment]
maybe from where you were messing with his scaling that one round? idk i deleted the slot & everything it's weird

**Comment by GeneriedJenelle** [comment]
Yeah scaling doesn't persist over rounds, only the changes to the actual teen scale data and your height will be added to the scale when you join a round.

**Pull request merged**
