### PR TITLE
Factory Rebrand: Aoki Incorporated

### PR DESCRIPTION
**Pull request by XanderDox**
This rebrands the Factory into an actual company, 'Aoki Incorporated' - an independent shipping and resource mining conglomerate that operates long-haul shipping between NanoTrasen colonies and Sol space. Here is some lore on Aoki Incorporated: https://docs.google.com/document/d/1uGHoRUullmZtRtcce1AzxsQCn1xOtS7USlPdbOxem1o/edit?usp=sharing

This PR changes the map, adds Aoki signs and minor redesigns of the factory spaces. It also fully establishes the factory as it's own business, and the Aoki Manager's independence from the micromanagement of the Mayor.

The factory roles now have new titles:
- The factory manager is now the 'Aoki Manager' or 'Aoki Supervisor'.
- Cargo Technicians are now 'Aoki Associate' or 'Shipping Technician' or 'Delivery Assistant'
- Miners are now 'Mining Technician' or 'Drill Technician'

Things that need tweaking:
- Door colours could be a bit obnoxious, had difficulty finding a colour to make them while matching the green aesthetic.
- I could not procure any good locker sprites to replace the old Cargo lockers, thus they remain orange. I will attempt to fix this in the coming months.

### CODE REVIEW

**Comment by XanderDox** [comment]
P.S I have no idea why there's a merge conflict with the map. Will need some investigating by someone more experienced.

**Comment by GeneriedJenelle** [comment]
I'll try get to this tomorrow.

**Comment by XanderDox** [comment]
@GeneriedJenelle you didnt get to it by tomorrow and now it's super outdated lol.

**Comment by ErwinSnowden** [comment]
aoki is a dumb name, so is the name incorporated, doesn't make sense from a scientific standpoint either since the distance between pollux and earth/sol makes it more costly to fly in resources instead of fund local mining operations, a better backstory is that the factory was new startup, which explains the recent acquisition of the factory by a conglomerate who operates in sol space on space wallstreet or however the stock market works in the 2200s. Which has lead to accelerated growth for the Blue Colony as a whole, since before the factories were localized[citation needed]. Doesn't have any glaring issues like "long haul space runs across the galaxies".

factory should've been independent from the get-go, but who owns the factory should stay random outside of extended/persistent rounds.

Also if you're going to do this, in the future you might want to add a special? fax machine that can contact Aoki Corp for aid or orders and just general role-play like sending quarterly reports and other business information.

**Pull request closed without merging**
