### PR TITLE
Navy tactical police armor Part 2: body armor in vendor

### PR DESCRIPTION
**Pull request by savethetreez**
## About The Pull Request
Replaces the tan tactical armor with the navy one in the armory equipment vendor (warning: helmet is being worked on, see part 3)

## Why It's Good For The Game
See PR#1267

## Changelog
:cl:
tweak: tweaked a few things
code: changed some code
/:cl:

### CODE REVIEW

**Comment by GeneriedJenelle** [comment]
PR isn't passing checks. Check this out.

```
code/game/machinery/vending.dm:2393:error: /obj/item/clothing/suit/armor/pcarrier/navy/policetactical: undefined type path
polaris.dmb - 1 error, 0 warnings (12/23/20 1:43 pm)
```

**Comment by savethetreez** [comment]
Yes, but now that the object actually exists, it should, I don't get why it's not working

**Comment by savethetreez** [comment]
Yay should work now

**Comment by savethetreez** [comment]
Should be good now

**Pull request merged**
