### PR TITLE
Adds Cannabis Permit Form

### PR DESCRIPTION
**Pull request by XanderDox**
## About The Pull Request

Adds a Cannabis Permit Form

## Why It's Good For The Game

Because City Hall can issue cannabis permits but has no way currently to do so.

## Changelog
:cl:
add: Adds a Cannabis Permit form under 'Council' in Load Templates.
/:cl:

### CODE REVIEW

**Comment by GeneriedJenelle** [comment]
We don't even have cannabis permits so what are we supposed to sell?

**Comment by XanderDox** [comment]
@GeneriedJenelle This is the permit itself.

**Comment by GeneriedJenelle** [comment]
Add a physical permit for this in permits.dm and I'll merge it.

**Comment by XanderDox** [comment]
Oki doki.

**Pull request closed without merging**
